- name: Converge
  hosts: all
  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

    - name: Install Base packages.
      ansible.builtin.package:
        name:
          - python3-pip
          - python3-docker
          - gnupg
          - curl
          - ca-certificates
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install docker
      ansible.builtin.include_role:
        name: geerlingguy.docker

    - name: Init swarm
      community.docker.docker_swarm:
        state: present

    - name: Create overlay network
      community.docker.docker_network:
        name: "alloy"
        driver: overlay
        attachable: true
        state: present
  tasks:
    - name: Include the role
      ansible.builtin.include_role:
        name: brpaz.swarm_grafana_alloy
      vars:
        alloy_cluster: "test"
        alloy_swarm_networks:
          - name: "alloy"
        alloy_integrations_node_exporter_enabled: true
